name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: gcc *.c -o ksuvot.exe
    - name: RUN
      run: ./ksuvot.exe
      
    - uses: actions/upload-artifact@v2
      with:
        name: ksuvot-artifact
        path: ksuvot.exe
        retention-days: 1
      
  send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: ksuvot-artifact

      - name: "Edit config"
        run: git config --global user.email "ksuvot36@yandex.ru" && git config --global user.name "Ksuvot"
      - name: "Version patch"
        run: npm version 0.1.$GITHUB_RUN_ID
    
      - name: "Telegram"
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: New 0.1.${{ github.run_id }} version publish
          document: ksuvot.exe
