name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: gcc *.c -o ksuvot.exe
    - name: RUN
      run: ./ksuvot.exe
      
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ksuvot.exe
      
    - name: "Telegram Notify"
      uses: "appleboy/telegram-action@master"
      with:
        to: ${{ secrets.TELEGRAM_TO_DEBUG }}
        token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
        message: ksuvot init
        document: ksuvot.exe
